# Generated by Django 5.2.13 on 2026-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_paragraph_one', models.TextField(blank=True)),
                ('about_paragraph_two', models.TextField(blank=True)),
                ('philosophy_title', models.CharField(blank=True, max_length=255)),
                ('philosophy_body', models.TextField(blank=True)),
                ('founders_title', models.CharField(blank=True, max_length=255)),
                ('founders_subtitle', models.TextField(blank=True)),
                ('values_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('lead', models.TextField(blank=True)),
                ('information_title', models.CharField(blank=True, max_length=120)),
                ('location_label', models.CharField(blank=True, max_length=80)),
                ('location_value', models.CharField(blank=True, max_length=255)),
                ('email_label', models.CharField(blank=True, max_length=80)),
                ('email_value', models.EmailField(blank=True, max_length=254)),
                ('website_label', models.CharField(blank=True, max_length=80)),
                ('website_value', models.URLField(blank=True)),
                ('form_title', models.CharField(blank=True, max_length=120)),
                ('form_action', models.URLField(blank=True)),
                ('form_subject', models.CharField(blank=True, max_length=255)),
                ('form_success_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('bio_primary', models.TextField()),
                ('bio_secondary', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('style_variant', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(choices=[('highlight', 'Highlight'), ('dark', 'Dark')], default='dark', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_watermark', models.CharField(blank=True, max_length=24)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('intro_title', models.CharField(blank=True, max_length=255)),
                ('intro_body', models.TextField(blank=True)),
                ('why_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('style_variant', models.CharField(choices=[('primary', 'Primary'), ('black', 'Black'), ('outlined', 'Outlined')], default='primary', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('services_title', models.CharField(blank=True, max_length=255)),
                ('industries_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_description', models.TextField(blank=True)),
                ('newsletter_title', models.CharField(blank=True, max_length=120)),
                ('newsletter_text', models.TextField(blank=True)),
                ('join_button_label', models.CharField(blank=True, max_length=80)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('developer_name', models.CharField(blank=True, max_length=120)),
                ('developer_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('style_variant', models.CharField(choices=[('primary', 'Primary'), ('black', 'Black')], default='primary', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
