DEFAULT_SITE_CONTENT = {
    "site_settings": {
        "footer_description": "Leon & Walker Talent Partners helps ambitious technology companies build sales teams that create measurable revenue impact.",
        "newsletter_title": "Subscribe Newsletter",
        "newsletter_text": "Subscribe us & receive our updates in your inbox directly.",
        "join_button_label": "Join Now",
        "join_button_url": "#",
        "facebook_url": "",
        "linkedin_url": "",
        "copyright_text": "Copyright 2026 Leon & Walker. Designed and developed by",
        "developer_name": "Confluxaa",
        "developer_url": "https://confluxaa.com/",
    },
    "home_page": {
        "hero_watermark": "L&W",
        "hero_title": "Leon & Walker Talent Partners",
        "hero_subtitle": "Specialist recruitment partner for tech sales roles across Enterprise, Mid-Market, and Startup ecosystems.",
        "hero_know_more_label": "Know More",
        "hero_know_more_url": "#intro",
        "intro_title": "We build High-Performing Sales Teams for the World's Most Ambitious Tech Companies",
        "intro_body": "Leon & Walker Talent Partners helps IT Services, SaaS, and Product Companies hire world-class Sales Talent faster and with real revenue impact. Whether you're scaling in India or building a global sales engine, we help you find sales professionals who don't just sell - they perform.",
        "intro_know_more_label": "Know More",
        "intro_know_more_url": "#",
        "why_title": "Why Companies Work With Us",
    },
    "home_features": [
        {
            "title": "Specialists in Tech Sales Hiring",
            "description": "We live and breathe IT and SaaS sales roles.",
            "image_path": "/assets/img/saas.png",
            "variant": "highlight",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 1,
        },
        {
            "title": "Peer-Led Candidate Evaluation",
            "description": "Each shortlisted candidate is reviewed by a senior sales leader on-demand.",
            "image_path": "/assets/img/icon-evaluation.svg",
            "variant": "dark",
            "display_order": 2,
        },
        {
            "title": "Precision over Volume",
            "description": "Only high-fit, sales-ready candidates.",
            "image_path": "/assets/img/icon-precision.svg",
            "variant": "dark",
            "display_order": 3,
        },
        {
            "title": "Faster Hiring Cycles",
            "description": "Up to 50% faster time-to-hire.",
            "image_path": "/assets/img/icon-hiring.svg",
            "variant": "dark",
            "display_order": 4,
        },
        {
            "title": "Global Reach",
            "description": "Talent across India, APAC, Middle East, UK, and North America.",
            "image_path": "/assets/img/icon-global.svg",
            "variant": "dark",
            "display_order": 5,
        },
    ],
    "about_page": {
        "hero_title": "Redefining tech Sales hiring",
        "hero_subtitle": "Through insight, integrity, and a partnership built on performance.",
        "hero_know_more_label": "Know More",
        "hero_know_more_url": "#about-main",
        "about_title": "About Us",
        "about_paragraph_one": "Leon & Walker Talent Partners is a specialist recruitment firm focused exclusively on Sales Recruitment for the Technology Industry - helping IT, SaaS, and Product companies across the globe build high-impact sales organizations.",
        "about_paragraph_two": "We believe the right sales hire can change everything. That's why our approach blends deep industry expertise, peer-led evaluation, and data-driven fitment - ensuring every hire contributes meaningfully to business growth.",
        "philosophy_title": "Our Philosophy",
        "philosophy_body": "We don't just fill roles - we help you build capability. Every sales hire strengthens your go-to-market execution, shortens revenue cycles, and fuels sustainable growth. We align with your business vision, talent priorities, and growth goals to deliver measurable hiring impact.",
        "founders_title": "Our founders",
        "founders_subtitle": "Specialists in sales recruitment for the technology industry - from proven leaders to high-impact teams.",
        "values_title": "Our Values",
    },
    "founders": [
        {
            "name": "Anuradha Prasad",
            "role": "Managing Partner",
            "quote": "Expert in building high-impact sales teams with deep roots in IT hiring and talent strategy.",
            "bio_primary": "Anuradha Prasad, Co-Founder at Leon & Walker, brings over two decades of expertise in IT hiring, sales recruitment, and GTM talent strategy. With a strong track record across the IT recruitment industry, she has helped organizations scale by building high-impact sales teams and leadership roles across global markets.",
            "bio_secondary": "At Leon & Walker, Anuradha combines her deep experience in end-to-end recruitment operations and consulting with a consultative, insight-driven approach, ensuring clients not only hire the best talent but also strengthen their overall sales capability and growth trajectory.",
            "image_path": "/assets/img/Rectangle 118.png",
            "style_variant": "primary",
            "display_order": 1,
        },
        {
            "name": "Raghavendra Prasad",
            "role": "Partner",
            "quote": "Trusted advisor in sales and leadership hiring, combining recruitment expertise with consulting insight.",
            "bio_primary": "Raghavendra Prasad, Partner at Leon & Walker, brings over 26 years of experience in sales, strategy, and growth across the IT and Recruitment Services ecosystem. A recognized leader in sales and leadership hiring, he specializes in building high-performing sales organizations by identifying and placing proven leaders who accelerate growth and market impact.",
            "bio_secondary": "At Leon & Walker, Raghavendra leverages his deep industry understanding and consultative leadership approach to help clients secure the talent that shapes their business future.",
            "image_path": "/assets/img/Rectangle 120.png",
            "style_variant": "secondary",
            "display_order": 2,
        },
    ],
    "values": [
        {
            "title": "Integrity",
            "description": "We deliver what we promise.",
            "image_path": "/assets/img/icon-integrity.svg",
            "style_variant": "primary",
            "display_order": 1,
        },
        {
            "title": "Insight",
            "description": "We understand capability beyond CVs.",
            "image_path": "/assets/img/icon-insight.svg",
            "style_variant": "black",
            "display_order": 2,
        },
        {
            "title": "Partnership",
            "description": "We work as an extension of your business.",
            "image_path": "/assets/img/icon-partnership.svg",
            "style_variant": "primary",
            "display_order": 3,
        },
        {
            "title": "Performance",
            "description": "Every placement is measured by impact.",
            "image_path": "/assets/img/icon-performance.svg",
            "style_variant": "primary",
            "display_order": 4,
        },
    ],
    "services_page": {
        "hero_title": "Dedicated Sales hiring partner",
        "hero_subtitle": "Combining industry insight, speed, and talent intelligence to deliver measurable results.",
        "hero_know_more_label": "Know More",
        "hero_know_more_url": "#services-list",
        "services_title": "Services",
        "industries_title": "Industries We Serve",
    },
    "service_cards": [
        {
            "title": "Sales Talent Acquisition",
            "image_path": "/assets/img/box1 pic.jpg",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 1,
        },
        {
            "title": "Recruitment-as-a-Service (RaaS)",
            "image_path": "/assets/img/box2 pic.jpg",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 2,
        },
        {
            "title": "Talent Intelligence & Market Insights",
            "image_path": "/assets/img/box3 pic.jpg",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 3,
        },
        {
            "title": "AI, Data & Emerging Tech Sales Hiring",
            "image_path": "/assets/img/box4 pic.jpg",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 4,
        },
    ],
    "industry_cards": [
        {
            "title": "IT Services & Consulting",
            "image_path": "/assets/img/icon-it-services.svg",
            "style_variant": "primary",
            "display_order": 1,
        },
        {
            "title": "SaaS & Product Companies",
            "image_path": "/assets/img/icon-saas-company.svg",
            "style_variant": "black",
            "display_order": 2,
        },
        {
            "title": "Data & AI Startups",
            "image_path": "/assets/img/icon-data-ai.svg",
            "style_variant": "primary",
            "display_order": 3,
        },
        {
            "title": "Global Capability Centers (GCCs)",
            "image_path": "/assets/img/icon-gcc.svg",
            "style_variant": "primary",
            "display_order": 4,
        },
        {
            "title": "Engineering & ER&D Companies",
            "image_path": "/assets/img/icon-engineering.svg",
            "style_variant": "outlined",
            "display_order": 5,
        },
    ],
    "resource_items": [
        {
            "title": "Candidate Hub",
            "description": "Join our global network of tech sales professionals and explore career opportunities with leading IT and SaaS firms across India, APAC, and beyond.",
            "image_path": "/assets/img/people-with-laptops-office 2 (2).png",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 1,
        },
        {
            "title": "Insights & Resources",
            "description": "Stay updated with hiring insights, market trends, and leadership conversations shaping the future of sales recruitment.",
            "image_path": "/assets/img/sales.png",
            "know_more_label": "Know More",
            "know_more_url": "#",
            "display_order": 2,
        },
    ],
    "contact_page": {
        "kicker": "Get In Touch",
        "title": "Let's Build Something Great",
        "lead": "For any query fill out the form, our team will contact you ASAP.",
        "information_title": "Contact Information",
        "location_label": "Location",
        "location_value": "Bangalore, Karnataka, India",
        "email_label": "Email",
        "email_value": "hello@leonwalker.com",
        "website_label": "Website",
        "website_value": "https://lw.com/",
        "form_title": "Send Us a Message",
        "form_action": "https://formsubmit.co/nikhil.confluxaa@gmail.com",
        "form_subject": "New Contact Us Query - Leon & Walker",
        "form_success_url": "https://confluxaa.com/",
    },
}
